### ISSUE TITLE
sudo ./attach error

### ISSUE THREAD

**Issue by Tomeo213** [oneechanhax/nekohook#34]
![obraz](https://user-images.githubusercontent.com/41307441/42782450-4430255e-8949-11e8-8826-c87f327c5835.png)
Any idea what to do? I have this from the beginning, had problems with this even with the old cathook.

**Comment by BenCat07** [comment]
never ever ever ever ever ever EVER use a ubtunu subsystem on windows for cathook, NEVER

**Comment by yessir20** [comment]
Same here, but I am using openSUSE

**Comment by yessir20** [comment]
NOW I AM TRYING TO USE ARCH BUT IT IS NOT EVEN A COMMAND
wait do i h ave latest version

**Comment by yessir20** [comment]
https://gyazo.com/8183a88b4c009f54d0bf36ba9593c00d

**Comment by yessir20** [comment]
![Screenshot_18](https://user-images.githubusercontent.com/68519843/87888404-969e4200-c9e1-11ea-8ac7-8fb974cd157e.png)

**Comment by oneechanhax** [comment]
Use your **OWN** injector.
or, read the readme.md.
