### ISSUE TITLE
sudo ./attach error for openSUSE subsystem

### ISSUE THREAD

**Issue by yessir20** [oneechanhax/nekohook#35]
help me or i will kill you

**Comment by yessir20** [comment]
now i am trying to use the ubuntu but it is still not working
do i have to use arch

**Comment by yessir20** [comment]
NOW IT IS EVEN SAYING GIT CLONE IS NOT A VALID COMMAND

**Comment by Midnoclose** [comment]
send proof bro

**Comment by yessir20** [comment]
now tf i just uninstalled let me reinstall and send proof

**Comment by yessir20** [comment]
[](https://gyazo.com/8183a88b4c009f54d0bf36ba9593c00d)

**Comment by yessir20** [comment]
![Screenshot_18](https://user-images.githubusercontent.com/68519843/87888446-ccdbc180-c9e1-11ea-8cda-478909f64b7b.png)

**Comment by Midnoclose** [comment]
bro what is that crop I can't even read it

**Comment by yessir20** [comment]
someone said it was not sudo ./attach
but what do i do

**Comment by oneechanhax** [comment]
just disable vac tf
